stages:
  - build
  - style
  - test
  - deploy

building:
  stage: build
  script:
    - (cd src/cat && make)
    - (cd src/grep && make)
    - mkdir artifacts 
    - cp src/cat/s21_cat src/grep/s21_grep artifacts
  artifacts:
    paths:
      - artifacts
    expire_in: 30 days

clanging:
  stage: style
  script:
    - cd src
    - cp ../materials/linters/.clang-format .
    - bash style.sh

testing:
  stage: test
  script:
    - (cd src/cat && make)
    - (cd src/grep && make)
    - cd src
    - cp ../materials/linters/.clang-format .
    - bash style.sh
    - echo all integration tests passed

deploying:
  stage: deploy
  script:
    - bash deploy.sh

